# Unbind the default Ctrl+b
unbind C-b

# Set the prefix to Ctrl+a
set -g prefix C-a

# Ensure Ctrl+a can still be sent to other apps (by pressing it twice)
bind C-a send-prefix


# Terminal and Display Settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on


# Splits
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"


# Press Prefix + r to reload the config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"


# Window Management
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# history-limit
set -g history-limit 50000

# Status line tweaks
set -g status-interval 1
set -g status-left-length 20

set -g window-status-format " #I:#W "
set -g window-status-current-format "#[fg=white,bold,bg=black] #I:#W* "

set -g status-right-length 120
set -g status-right "#[fg=brightwhite,bg=blue,bold]  #(cat ~/.config/tmux/attacker_ip 2>/dev/null || echo 'No IP') #[fg=white,bg=red,bold]  #(cat ~/.config/tmux/target_ip 2>/dev/null || echo 'No IP') #[fg=black,bg=green,bold] %H:%M:%S "
